### ISSUE TITLE
Dark Reader compatibility 

### ISSUE THREAD

**Issue by vegeta897** [vegeta897/snow-stamp#158]
The [Dark Reader](https://darkreader.org/) extension causes the custom toggle switches to disappear, because their background colors are changed to match the page background.

Default:
![image](https://user-images.githubusercontent.com/1789096/152517639-b6c50ac5-2b16-4f5b-a284-3f74392e482b.png)
![image](https://user-images.githubusercontent.com/1789096/152517671-dfee46a9-5dee-4062-b468-7d457acaa0f1.png)

Dark Reader:
![image](https://user-images.githubusercontent.com/1789096/152517734-a8ae6516-a43c-4609-afb4-0ebe57c386c9.png)
![image](https://user-images.githubusercontent.com/1789096/152517811-571aca52-a646-4c92-97d8-573aafd51121.png)

I will try to see if there's a way I can prevent this from happening. As a last resort, I can contribute custom CSS rules to the Dark Reader repo itself, see: https://github.com/darkreader/darkreader/blob/master/CONTRIBUTING.md#fixing-incorrect-inversions

**Comment by p0lygun** [comment]
can confirm 👍

**Comment by vegeta897** [comment]
Just as I was about to start working on this I turned the extension on and saw this:

![image](https://user-images.githubusercontent.com/1789096/152907824-d90cf7f5-2154-4457-9f80-c068d87badbe.png)
![image](https://user-images.githubusercontent.com/1789096/152907832-12543661-5c09-4178-828d-ce9f68628a20.png)

There was an update to the extension yesterday, but I don't think that affected this because it will still be invisible _sometimes, randomly_ if I keep refreshing (in my local dev environment anyway).

Either way, it still doesn't look so great so I'll try to improve it.

**Comment by vegeta897** [comment]
I changed the switch itself to use border-color instead of background-color so Dark Reader doesn't change it as drastically.

This is what it looks like now:
![image](https://user-images.githubusercontent.com/1789096/152915631-b6271b7b-bec9-458e-a784-58669732e23a.png)
![image](https://user-images.githubusercontent.com/1789096/152915641-2fd1ab43-53bf-4ee0-88fb-adb316a1325d.png)

I'm happy with this!

I also slightly darkened the switch and its background, without Dark Reader:
![image](https://user-images.githubusercontent.com/1789096/152915730-3ae07a89-56c5-4a9e-b107-1609e2729b5d.png)
![image](https://user-images.githubusercontent.com/1789096/152915734-b8053da4-7929-4498-a202-b1c7954374a1.png)
