### ISSUE TITLE
Snowflake timestamp in the future

### ISSUE THREAD

**Issue by seizu** [vegeta897/snow-stamp#26]
Hi! 
I have written a discord_chat hook with selenium, 
when I compare the snowflake with the timestamp of the received message, the snowflake timestamp is in the future, it differs by 600ms. 

Log: chat-messages___chat-messages-828248808311357441
`2021-04-04T12:45:03.476Z : Incoming msg: [ 14:45 ] ergo : hh>`

Diff: received-ts: 2021-04-04T12:45:03.476Z minus sf-ts:2021-04-04T12:45:04.020Z = -544.15625ms

Strange because, yesterday it worked, today it doesn't. My Local Time is in sync!

**Comment by vegeta897** [comment]
Hello! Unfortunately I can't help you here 😟

Snow-Stamp simply extracts the timestamp of the snowflake provided by Discord. Any issue with this timestamp not being accurate is outside of my control and the scope of this project.
