### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by ChildishGiant** [vegeta897/snow-stamp#3]
![image](https://user-images.githubusercontent.com/13716824/56958948-c5fa3200-6b43-11e9-88c2-73c4e3ef387a.png)
![image](https://user-images.githubusercontent.com/13716824/56958968-d01c3080-6b43-11e9-90ec-14ff01ef1a6d.png)
![image](https://user-images.githubusercontent.com/13716824/56958982-df02e300-6b43-11e9-8925-fe3065cc242c.png)

**Comment by vegeta897** [comment]
Sorry about that. I updated nginx to force https on snow-stamp but I did it wrong. It should be okay now, thanks for reporting.
