### ISSUE TITLE
CORS header "Access-Control-Allow-Origin" missing

### ISSUE THREAD

**Issue by Huddlect** [vegeta897/snow-stamp#4]
I don't know what that means but Firefox reported that it couldn't load the fonts because of it.

`downloadable font: download failed (font-family: "Icons" style:normal weight:400 stretch:100 src index:1): bad URI or cross-site access not allowed source: https://pixelatomy.com/snow-stamp/static/media/icons.af7ae505.woff2`

`downloadable font: download failed (font-family: "Icons" style:normal weight:400 stretch:100 src index:2): bad URI or cross-site access not allowed source: https://pixelatomy.com/snow-stamp/static/media/icons.fee66e71.woff`

`downloadable font: download failed (font-family: "Icons" style:normal weight:400 stretch:100 src index:3): bad URI or cross-site access not allowed source: https://pixelatomy.com/snow-stamp/static/media/icons.b06871f2.ttf`

**Comment by vegeta897** [comment]
Thanks for the report. This appears to happen when visiting `https://www.pixelatomy.com/snow-stamp` instead of `https://pixelatomy.com/snow-stamp
`
I'll have to get around to fixing this on my server, but for now just fix your bookmark if it has the `www`

**Comment by Huddlect** [comment]
I did and that did the trick. Thanks for the quick response. I visited the www domain because it appeared in the DuckDuckGo search results for "discord snowflake to timestamp" btw.
