### ISSUE TITLE
If an invalid snowflake is entered, the URL query parameter of the snowflake gets stuck at the invalid snowflake

### ISSUE THREAD

**Issue by bru53001** [vegeta897/snow-stamp#45]
![Screenshot_188](https://user-images.githubusercontent.com/79501858/118500297-58bc9800-b730-11eb-832a-fa483481926e.png)
Like in this screenshot, if you enter an invalid snowflake, it gets stuck at that snowflake and you have to re-enter a valid snowflake into the URL for it to work again.

**Comment by vegeta897** [comment]
Thanks for reporting, I will check this out!

**Comment by bru53001** [comment]
![Screenshot_229](https://user-images.githubusercontent.com/79501858/118703530-de1e7600-b81e-11eb-85ce-5ca0b99dc1b0.png)
Alright, everything looks good now.
