### ISSUE TITLE
Incorrect timezone text displayed, but time is correct for correct timezone.

### ISSUE THREAD

**Issue by KandiPanda** [vegeta897/snow-stamp#90]
For example, for the snowflake `875220877896200262`, it displays as
`Central Standard Time`
`8/11/2021, 10:35:18 PM`
when it should instead be displaying as
`Central Daylight Time`
`8/11/2021, 10:35:18 PM`

(It's showing the correct UTC-5 time for CDT, but not _quite_ the correct timezone text for it.)

Simply using the ambiguous "Central Time" rather than coding it to show the correct Standard/Daylight text would probably be an acceptable solution with less work involved, though a less precise solution.

**Comment by vegeta897** [comment]
This is interesting because that time zone comes right from your browser.

- Can you tell me what browser you're using?
- Can you try any other browsers?

**Comment by vegeta897** [comment]
Also, can you open this page and show/tell me what you see?

https://run.plnkr.co/preview/cks8fnjj500073b6cuoq2ml0t/

**Comment by KandiPanda** [comment]
Currently using Waterfox Classic (on Win7 Ultimate x64, if OS matters). 
(Being a fork of Firefox, it may behave similarly in Firefox and/or other Firefox-based browsers? Haven't had actual Firefox installed since I stopped using Firefox ESR 52.x though.)
Also checked the browser console just in case, no errors shown there.

Tried the site in the CEF browser embedded in Steam, it does show as "Central Daylight Time" there.
(I would imagine that normal Chrome/Chromium would behave similarly, if I had it installed.)

Went to that jsfiddle page in both, here are the output consoles: 

Waterfox Classic: 
![Time_Zone_Name_Test_(Waterfox_Classic)](https://user-images.githubusercontent.com/43508599/129144988-cf96bff5-8ec5-4a49-b9c9-c7e70ed03d28.png)
Steam/CEF: 
![Time_Zone_Name_Test_(Steam_CEF)](https://user-images.githubusercontent.com/43508599/129145000-fcebcf93-a2e6-49b6-b0dc-bdd2893acca0.png)

**Comment by vegeta897** [comment]
Thank you!

I would certainly classify this as a bug in Waterfox Classic since `Date.toString()` is simply not reporting the correct time zone.

But the good news is that it does report the correct time zone in the second method in that fiddle, so I will go ahead and update Snow-Stamp to use that new method.

Thanks for bringing this to my attention!

**Comment by vegeta897** [comment]
This should be fixed with 8e249c2.
